#!/bin/bash 

oldname=cgl.quakesim.simplex
newname=cgl.quakesim.simplex

for filename in "$@"; do
    if [ -f $filename ]; then
        sed "s/$oldname/$newname/" < $filename > tmp
        mv tmp $filename
    fi
done   

