package gekmlib;
/**
 * AutoGenerated.
 *
 */

import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
abstract public class Geometry extends ObjectNode
{


    public Geometry()
    {
        super();
    }

    public Geometry(Node parent)
    {
        super(parent);
    }



    public Object clone() throws CloneNotSupportedException
    {
        Geometry result = (Geometry)super.clone();
        return result;
    }
    public void setRecursiveNotDirty()
    {
        super.setRecursiveNotDirty();
    }
}
