<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://infogroup.usc.edu:8080/axis/services/Select" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://infogroup.usc.edu:8080/axis/services/Select" xmlns:intf="http://infogroup.usc.edu:8080/axis/services/Select" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><wsdl:types/>
  <wsdl:message name="selectRequest">
    <wsdl:part name="in0" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="selectResponse">
    <wsdl:part name="selectReturn" type="xsd:string"/>
  </wsdl:message>
  <wsdl:portType name="Select">
    <wsdl:operation name="select" parameterOrder="in0">
      <wsdl:input message="intf:selectRequest" name="selectRequest"/>
      <wsdl:output message="intf:selectResponse" name="selectResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SelectSoapBinding" type="intf:Select">
    <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="select">
      <wsdlsoap:operation soapAction=""/>
      <wsdl:input name="selectRequest">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://infogroup.usc.edu:8080/axis/services/Select" use="encoded"/>
      </wsdl:input>
      <wsdl:output name="selectResponse">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://infogroup.usc.edu:8080/axis/services/Select" use="encoded"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SelectService">
    <wsdl:port binding="intf:SelectSoapBinding" name="Select">
      <wsdlsoap:address location="http://infogroup.usc.edu:8080/axis/services/Select"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>