package cgl.webservices.KmlGenerator.gekmlib;
/**
 * AutoGenerated.
 *
 */

import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
public class innerBoundaryIs extends boundary
{


    public innerBoundaryIs()
    {
        super();
    }

    public innerBoundaryIs(Node parent)
    {
        super(parent);
    }



    public Object clone() throws CloneNotSupportedException
    {
        innerBoundaryIs result = (innerBoundaryIs)super.clone();
        return result;
    }
    public void setRecursiveNotDirty()
    {
        super.setRecursiveNotDirty();
    }
}
